cf-exports.tf, cf-exports.yml, db-subnet.tf, nacl-private.tf, nacl-public.tf, nacl-secure.tf, nacl-transit.tf
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
=> CloudFormation export + TF 0.12 support

LICENSE
Closes: #3
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
=> Adds Apache license file

_data.tf, _outputs.tf, _variables.tf, cf-exports.tf, db-subnet.tf, nacl-private.tf, nacl-public.tf, nacl-secure.tf, nacl-transit.tf, nat.tf, subnet-private.tf, subnet-public.tf, subnet-secure.tf, subnet-transit.tf, versions.tf, vpc-flow-logs.tf, vpc.tf
Closes: #5
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
=> Move code style to version 0.12 conventions

_variables.tf
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
=> Fix quoted type constraints deprecation

_variables.tf, vpc-endpoints.tf
- A vpc endpoint will be created based on the service name
- A security group will be created and attached to the endpoint
=> Aws vpc endpoints

README.md, _outputs.tf
Fixing outputs that had a list in a list to a flat list (as it should be) and adding extra outputs like NACLs
=> Fixing outputs and adding nacls

README.md, _outputs.tf, _variables.tf, nat.tf
=> Add capabilities to dynamically  Bring Your Own Elastic IP for Nat Gateway

README.md, _variables.tf, subnet-private.tf, vpc-endpoint-dynamodb.tf, vpc-endpoint-s3.tf
=> DynamoDB Gateway Endpoint

README.md, _variables.tf, s3-endpoint.tf
=> Add capability to change S3 endpoint policy

s3-endpoint.tf
=> Fix s3 endpoint policy

README.md, _variables.tf, db-subnet.tf, nacl-private.tf, nacl-public.tf, nacl-secure.tf, nacl-transit.tf, nat.tf, subnet-private.tf, subnet-public.tf, subnet-secure.tf, subnet-transit.tf, vpc-endpoint-dynamodb.tf, vpc-endpoint-s3.tf, vpc-endpoints.tf, vpc-flow-logs.tf, vpc.tf
=> Making flexible naming

network-firewall.tf
=> Fix default ingress rule Network Firewall

README.md, _variables.tf, network-firewall.tf
Change variable firewall_custom_rules string to list:
**network.tf**
```
module …
```
=> Update string to list for custom rules

README.md, _variables.tf, network-firewall.tf
=> add a bool that allows the default stateful rule to be on or off

network-firewall.tf
=> fix resource rule dependencies inside of network-firewall

.github/workflows/lint.yml, README.md, _data.tf, _variables.tf, dynamodb-endpoint.tf, nacl-secure.tf, nacl-transit.tf, subnet-private.tf, subnet-public.tf, subnet-secure.tf, subnet-transit.tf, versions.tf, vpc-endpoints.tf
- [ x I have added necessary documentation (if appropriate).
- [ x Any dependent changes have been merged and published in downstream modules.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …
=> Policy for VPC endpoints and enable dynamodb gateway endpoint

README.md, _variables.tf, network-firewall.tf
=> Add support for stateful rules created ousite the module

README.md, _variables.tf, nacl-private.tf, nacl-public.tf, nacl-secure.tf, nacl-transit.tf, nat.tf
=> 🔧 Add vpc_cidr_summ variable to reduce the number of NACL rules used

README.md, _variables.tf, vpc-flow-logs.tf
Create the possibility to encrypt the VCP Flow Logs Cloudwatch Log Group using KMS Customer Managed Keys (CMK)
=> Ensure the CloudWatch Log Group is encrypted by KMS/CMK 

vpc-endpoints.tf
- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] Any dependent changes have been merged and published in downstream modules.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> fix endpoint allowed cidrs try

README.md, _variables.tf
=> Fix unknown type boolean

.github/workflows/docs.yml, .github/workflows/lint.yml, .tflint.hcl, README.md, _outputs.tf, _variables.tf, cf-exports.tf, db-subnet.tf, nacl-private.tf, nacl-public.tf, nacl-secure.tf, nacl-transit.tf, nat.tf, versions.tf
=> Pump terraform required version and remove experiments (continuing from #46)

README.md, _variables.tf, cf-exports.tf, db-subnet.tf, nacl-public.tf, nacl-secure.tf
=> Allow public and secure connection
